import { StyleSheet } from "react-native";
import { colors } from "../global";

const viewStyles = StyleSheet.create( {
  shadow: {
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 1,
    shadowRadius: 3,
  },
  plantFilter: {
    bottom: 250,
    position: "absolute",
    alignItems: "center",
    gap: 12,
  },
  landscapeHelpBubble: {
    bottom: 128,
    width: 293,
    position: "absolute",
    borderRadius: 20,
    paddingVertical: 15,
    paddingHorizontal: 20,
    backgroundColor: colors.seekForestGreen,
  },
  landscapeHelpBubbleSpecies: {
    backgroundColor: colors.seekGreen,
  },
  helpBubble: {
    bottom: 210,
    width: 293,
    position: "absolute",
  },
  cameraZoomPresetsContainer: {
    position: "absolute",
    bottom: 104,
    left: 0,
    right: 0,
    alignItems: "center",
  },
  cameraZoomPresetsContainerLandscape: {
    position: "absolute",
    bottom: 24,
    left: 0,
    right: 0,
    alignItems: "center",
  },
  manualFocusSliderContainer: {
    position: "absolute",
    bottom: 154,
    left: 0,
    right: 0,
    alignItems: "center",
  },
  manualFocusSliderContainerLandscape: {
    position: "absolute",
    bottom: 76,
    left: 0,
    right: 0,
    alignItems: "center",
  },
  peakingSensitivitySliderContainer: {
    position: "absolute",
    bottom: 204,
    left: 0,
    right: 0,
    alignItems: "center",
  },
  peakingSensitivitySliderContainerLandscape: {
    position: "absolute",
    bottom: 128,
    left: 0,
    right: 0,
    alignItems: "center",
  },
  secondaryCameraControlsContainer: {
    position: "absolute",
    right: 0,
    top: 0,
    bottom: 0,
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 18,
    gap: 16,
  },
  secondaryCameraControlsContainerLandscape: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 24,
    gap: 16,
  },
  cameraControlsContainer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 32,
    paddingBottom: 31,
  },
  cameraControlsContainerLandscape: {
    position: "absolute",
    right: 0,
    top: 0,
    bottom: 0,
    flexDirection: "column",
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 32,
    gap: 50,
  },
  leftControls: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    width: 130,
    height: 60,
  },
  rightControls: {
    justifyContent: "center",
    width: 130,
    height: 60,
    alignItems: "center",
  },
  saveForLaterButton: {
    position: "absolute",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    alignItems: "center",
    justifyContent: "center",
    borderColor: colors.white,
    borderWidth: 2,
    borderRadius: 30,
    width: 56,
    height: 56,
  },
  saveForLaterButtonPortrait: {
    bottom: 112,
    left: 32,
  },
  saveForLaterButtonLandscape: {
    bottom: 32,
    left: 32,
  },
  saveForLaterBadge: {
    position: "absolute",
    top: -4,
    right: -4,
    minWidth: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: colors.seekGreen,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 5,
    borderColor: colors.white,
    borderWidth: 1,
  },
  galleryButton: {
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    alignItems: "center",
    justifyContent: "center",
    borderColor: "white",
    borderWidth: 2,
    borderRadius: 10,
    padding: 16,
    width: 60,
    height: 60,
  },
} );

const textStyles = StyleSheet.create( {
  scanText: {
    textAlign: "center",
  },
  saveForLaterBadgeText: {
    color: colors.white,
    fontSize: 13,
    fontWeight: "700",
    textAlign: "center",
  },
  textShadow: {
    textShadowColor: colors.textShadow,
    textShadowOffset: { width: -1, height: 1 },
    textShadowRadius: 3,
  },
} );

const imageStyles = StyleSheet.create( {
  gallery: {
    height: 24,
    width: 24,
  },
} );

export {
  viewStyles,
  textStyles,
  imageStyles,
};
